/**
 * Constantes de dominio: Accidentalidad
 *
 * Tipos de accidente, vehiculo, persona y lesion (con valores exactos del CSV
 * Anthem_CTC_Accidentalidad.csv), mapeos de severidad, condiciones meteorologicas
 * y factores de riesgo.
 */

const TIPOS_ACCIDENTE = {
  ALCANCE: 'ALCANCE',
  ATROPELLO_A_ANIMAL: 'ATROPELLO_A_ANIMAL',
  ATROPELLO_A_PERSONA: 'ATROPELLO_A_PERSONA',
  CAIDA: 'CAÍDA',
  CHOQUE_CONTRA_OBSTACULO_FIJO: 'CHOQUE_CONTRA_OBSTÁCULO_FIJO',
  COLISION_FRONTAL: 'COLISIÓN_FRONTAL',
  COLISION_FRONTO_LATERAL: 'COLISIÓN_FRONTO-LATERAL',
  COLISION_LATERAL: 'COLISIÓN_LATERAL',
  COLISION_MULTIPLE: 'COLISIÓN_MÚLTIPLE',
  DESPEÑAMIENTO: 'DESPEÑAMIENTO',
  OTRO: 'OTRO',
  SOLO_SALIDA_DE_LA_VIA: 'SOLO_SALIDA_DE_LA_VÍA',
  VUELCO: 'VUELCO'
};

const TIPOS_VEHICULO = {
  AMBULANCIA_SAMUR: 'AMBULANCIA_SAMUR',
  AUTOBUS_EMT: 'AUTOBUS_EMT',
  AUTOBUS: 'AUTOBÚS',
  AUTOBUS_ARTICULADO: 'AUTOBÚS_ARTICULADO',
  AUTOBUS_ARTICULADO_EMT: 'AUTOBÚS_ARTICULADO_EMT',
  AUTOCARAVANA: 'AUTOCARAVANA',
  BICICLETA: 'BICICLETA',
  BICICLETA_EPAC: 'BICICLETA_EPAC_(PEDALEO_ASISTIDO)',
  CAMION_DE_BOMBEROS: 'CAMIÓN_DE_BOMBEROS',
  CAMION_RIGIDO: 'CAMIÓN_RÍGIDO',
  CICLO: 'CICLO',
  CICLOMOTOR: 'CICLOMOTOR',
  CICLOMOTOR_DOS_RUEDAS: 'CICLOMOTOR_DE_DOS_RUEDAS_L1E-B',
  CICLOMOTOR_TRES_RUEDAS: 'CICLOMOTOR_DE_TRES_RUEDAS',
  CUADRICICLO_LIGERO: 'CUADRICICLO_LIGERO',
  CUADRICICLO_NO_LIGERO: 'CUADRICICLO_NO_LIGERO',
  FURGONETA: 'FURGONETA',
  MAQUINARIA_AGRICOLA: 'MAQUINARIA_AGRÍCOLA',
  MAQUINARIA_DE_OBRAS: 'MAQUINARIA_DE_OBRAS',
  MOTO_TRES_RUEDAS_MAS_125CC: 'MOTO_DE_TRES_RUEDAS_>_125CC',
  MOTO_TRES_RUEDAS_HASTA_125CC: 'MOTO_DE_TRES_RUEDAS_HASTA_125CC',
  MOTOCICLETA_MAS_125CC: 'MOTOCICLETA_>_125CC',
  MOTOCICLETA_HASTA_125CC: 'MOTOCICLETA_HASTA_125CC',
  OTROS_VEHICULOS_CON_MOTOR: 'OTROS_VEHÍCULOS_CON_MOTOR',
  OTROS_VEHICULOS_SIN_MOTOR: 'OTROS_VEHÍCULOS_SIN_MOTOR',
  PATINETE: 'PATINETE',
  REMOLQUE: 'REMOLQUE',
  SEMIREMOLQUE: 'SEMIREMOLQUE',
  SIN_ESPECIFICAR: 'SIN_ESPECIFICAR',
  TAXI: 'TAXI',
  TODO_TERRENO: 'TODO_TERRENO',
  TRACTOCAMION: 'TRACTOCAMIÓN',
  TREN_METRO: 'TREN/METRO',
  TURISMO: 'TURISMO',
  VEHICULO_ARTICULADO: 'VEHÍCULO_ARTICULADO',
  VMU_ELECTRICO: 'VMU_ELÉCTRICO'
};

const TIPOS_PERSONA = {
  CONDUCTOR: 'CONDUCTOR',
  PEATÓN: 'PEATÓN',
  TESTIGO: 'TESTIGO',
  VIAJERO: 'VIAJERO',
  PASAJERO: 'PASAJERO'
};

const TIPOS_LESION = {
  ASISTENCIA_SANITARIA_AMBULATORIA_CON_POSTERIORIDAD: 'ASISTENCIA_SANITARIA_AMBULATORIA_CON_POSTERIORIDAD',
  ASISTENCIA_SANITARIA_INMEDIATA_EN_CENTRO_DE_SALUD_O_MUTUA: 'ASISTENCIA_SANITARIA_INMEDIATA_EN_CENTRO_DE_SALUD_O_MUTUA',
  ASISTENCIA_SANITARIA_SÓLO_EN_EL_LUGAR_DEL_ACCIDENTE: 'ASISTENCIA_SANITARIA_SÓLO_EN_EL_LUGAR_DEL_ACCIDENTE',
  ATENCIÓN_EN_URGENCIAS_SIN_POSTERIOR_INGRESO: 'ATENCIÓN_EN_URGENCIAS_SIN_POSTERIOR_INGRESO',
  FALLECIDO_24_HORAS: 'FALLECIDO_24_HORAS',
  INGRESO_INFERIOR_O_IGUAL_A_24_HORAS: 'INGRESO_INFERIOR_O_IGUAL_A_24_HORAS',
  INGRESO_SUPERIOR_A_24_HORAS: 'INGRESO_SUPERIOR_A_24_HORAS',
  SE_DESCONOCE: 'SE_DESCONOCE',
  SIN_ASISTENCIA_SANITARIA: 'SIN_ASISTENCIA_SANITARIA',
  // Alias para compatibilidad con codigo existente
  LEVE: 'ASISTENCIA_SANITARIA_SÓLO_EN_EL_LUGAR_DEL_ACCIDENTE',
  GRAVE: 'INGRESO_SUPERIOR_A_24_HORAS',
  FALLECIDO: 'FALLECIDO_24_HORAS',
  DESCONOCIDO: 'SE_DESCONOCE'
};

const MAPEO_SEVERIDAD_LESIONES = {
  GRAVES: [
    'FALLECIDO_24_HORAS',
    'INGRESO_SUPERIOR_A_24_HORAS',
    'INGRESO_INFERIOR_O_IGUAL_A_24_HORAS',
    'ATENCIÓN_EN_URGENCIAS_SIN_POSTERIOR_INGRESO'
  ],
  LEVES: [
    'ASISTENCIA_SANITARIA_AMBULATORIA_CON_POSTERIORIDAD',
    'ASISTENCIA_SANITARIA_INMEDIATA_EN_CENTRO_DE_SALUD_O_MUTUA',
    'ASISTENCIA_SANITARIA_SÓLO_EN_EL_LUGAR_DEL_ACCIDENTE',
    'SIN_ASISTENCIA_SANITARIA'
  ],
  DESCONOCIDAS: ['SE_DESCONOCE']
};

const WEATHER_CONDITIONS = {
  DESPEJADO: 'DESPEJADO',
  NUBLADO: 'NUBLADO',
  LLUVIA_DEBIL: 'LLUVIA_DEBIL',
  LLUVIA_INTENSA: 'LLUVIA_INTENSA',
  GRANIZANDO: 'GRANIZANDO',
  NEVANDO: 'NEVANDO',
  SE_DESCONOCE: 'SE_DESCONOCE',
  NIEBLA: 'NIEBLA',
  VIENTO_FUERTE: 'VIENTO_FUERTE',
  NULL: 'NULL',
  DESCONOCIDO: 'SE_DESCONOCE'
};

const FACTORES_RIESGO = {
  ALCOHOL: 'ALCOHOL',
  DROGAS: 'DROGAS',
  VELOCIDAD_INADECUADA: 'VELOCIDAD_INADECUADA',
  CONDICIONES_METEOROLOGICAS: 'CONDICIONES_METEOROLOGICAS',
  HORA_MADRUGADA: 'HORA_MADRUGADA',
  VEHICULO_DOS_RUEDAS: 'VEHICULO_DOS_RUEDAS',
  ZONA_ACCIDENTES_FRECUENTES: 'ZONA_ACCIDENTES_FRECUENTES'
};

module.exports = {
  TIPOS_ACCIDENTE,
  TIPOS_VEHICULO,
  TIPOS_PERSONA,
  TIPOS_LESION,
  MAPEO_SEVERIDAD_LESIONES,
  WEATHER_CONDITIONS,
  FACTORES_RIESGO
};
