/**
 * Constantes de dominio: Patinetes Electricos
 *
 * Niveles de densidad, dominancia, concentracion de mercado, tipos de zona,
 * proveedores conocidos, umbrales y areas clave de la ciudad.
 */

const NIVELES_DENSIDAD_PATINETES = {
  BAJA: 'BAJA',
  MEDIA: 'MEDIA',
  ALTA: 'ALTA',
  MUY_ALTA: 'MUY_ALTA'
};

const DOMINANCIA_PROVEEDORES_PATINETES = {
  EQUILIBRADA: 'EQUILIBRADA',
  MONOPOLIO: 'MONOPOLIO',
  DUOPOLIO: 'DUOPOLIO',
  OLIGOPOLIO: 'OLIGOPOLIO'
};

const CONCENTRACION_MERCADO_PATINETES = {
  COMPETITIVA: 'COMPETITIVA',
  MODERADA: 'MODERADA',
  CONCENTRADA: 'CONCENTRADA',
  ALTA_CONCENTRACION: 'ALTA_CONCENTRACION'
};

const TIPOS_ZONA_PATINETES = {
  CENTRO_URBANO: 'CENTRO_URBANO',
  ZONA_COMERCIAL: 'ZONA_COMERCIAL',
  ZONA_RESIDENCIAL: 'ZONA_RESIDENCIAL',
  ZONA_UNIVERSITARIA: 'ZONA_UNIVERSITARIA',
  ZONA_TURISTICA: 'ZONA_TURISTICA',
  ZONA_EMPRESARIAL: 'ZONA_EMPRESARIAL',
  PERIFERIA: 'PERIFERIA',
  ZONA_TRANSPORTE: 'ZONA_TRANSPORTE'
};

const NIVELES_PRIORIDAD_PATINETES = {
  BAJA: 'BAJA',
  MEDIA: 'MEDIA',
  ALTA: 'ALTA',
  CRITICA: 'CRITICA'
};

const NIVELES_DEMANDA_PATINETES = {
  BAJA: 'BAJA',
  MEDIA: 'MEDIA',
  ALTA: 'ALTA',
  MUY_ALTA: 'MUY_ALTA'
};

const PROVEEDORES_PATINETES = {
  ACCIONA: 'ACCIONA',
  BIRD: 'BIRD',
  FLASH: 'FLASH',
  JUMP_UBER: 'JUMP_UBER',
  KOKO: 'KOKO',
  LIME: 'LIME',
  MOVO: 'MOVO',
  MYGO: 'MYGO',
  REBY_RIDES: 'REBY_RIDES',
  RIDECONGA: 'RIDECONGA',
  SJV_CONSULTING: 'SJV_CONSULTING',
  TAXIFY: 'TAXIFY',
  UFO: 'UFO',
  WIND: 'WIND'
};

const TIPOS_INFORME_PATINETES = {
  PROVEEDORES: 'proveedores',
  UBICACION: 'ubicacion',
  TOTALES: 'totales'
};

const UMBRALES_DENSIDAD_PATINETES = {
  MUY_ALTA: 200,
  ALTA: 100,
  MEDIA: 50,
  BAJA: 0
};

const UMBRALES_DEMANDA_PATINETES = {
  MUY_ALTA: 150,
  ALTA: 100,
  MEDIA: 50,
  BAJA: 0
};

// Indice Herfindahl-Hirschman (HHI = suma de cuadrados de participaciones, 0-10000)
const UMBRALES_CONCENTRACION_MERCADO = {
  HIGH: 5000,
  MODERATE: 2500,
  LOW: 1500,
  COMPETITIVE: 0
};

const AREAS_CLAVE_PATINETES = {
  CENTRAL: ['CENTRO', 'SOL'],
  UNIVERSITY: ['UNIVERSIDAD', 'CAMPUS'],
  TRANSPORT: ['ATOCHA', 'CHAMARTIN'],
  COMMERCIAL: ['RETIRO', 'SALAMANCA']
};

const SCOOTER_AGGREGATION_FIELDS = {
  DISTRITO: 'distrito',
  BARRIO: 'barrio'
};

module.exports = {
  NIVELES_DENSIDAD_PATINETES,
  DOMINANCIA_PROVEEDORES_PATINETES,
  CONCENTRACION_MERCADO_PATINETES,
  TIPOS_ZONA_PATINETES,
  NIVELES_PRIORIDAD_PATINETES,
  NIVELES_DEMANDA_PATINETES,
  PROVEEDORES_PATINETES,
  TIPOS_INFORME_PATINETES,
  UMBRALES_DENSIDAD_PATINETES,
  UMBRALES_DEMANDA_PATINETES,
  UMBRALES_CONCENTRACION_MERCADO,
  AREAS_CLAVE_PATINETES,
  SCOOTER_AGGREGATION_FIELDS
};
