/**
 * Codigos de error unificados de la API
 *
 * Permite a los clientes detectar tipos de error sin parsear el campo `message`.
 * Cada codigo es estable y se mantiene aunque cambien los mensajes en espanol.
 *
 * Convencion: SCREAMING_SNAKE_CASE en ingles (infraestructura compartida).
 * El campo `message` sigue en espanol (regla del proyecto).
 */

const ERROR_CODES = {
  // Generales
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  TIMEOUT: 'TIMEOUT',

  // Autenticacion / Autorizacion
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  PASSWORD_WEAK: 'PASSWORD_WEAK',
  USER_EXISTS: 'USER_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Rate limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Recursos de dominio
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  INVALID_OBJECT_ID: 'INVALID_OBJECT_ID',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  INVALID_GEO_BOUNDS: 'INVALID_GEO_BOUNDS',

  // Base de datos
  DATABASE_ERROR: 'DATABASE_ERROR',
  DUPLICATE_KEY: 'DUPLICATE_KEY',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED'
};

module.exports = ERROR_CODES;
